### ISSUE TITLE
Only the first line of output shows on the console

### ISSUE THREAD

**Issue by svanimpe** [swiftwasm/uwasi#2]
When I run the following Swift code:

```swift
print("First")
print("Second")
```

Only "First" shows up in the console

**Comment by filip-sakel** [comment]
This is likely a buffering problem. Libc's `fwrite` buffers text for most files until `fflush` is called. For tty files (terminal outputs, such as console.log) there should be different buffering; they should be updated after each `\n` character, I believe. To determine the buffering behavior, `fwrite` calls `fstat` before writing anything. The problem might be that fstat is [not implemented](https://github.com/swiftwasm/uwasi/blob/331ac54b0076583622cb5d1ed33482015b0b4f48/src/features/fd.ts#L124). Thus, Libc doesn't know that stdout is a tty.
